### ISSUE TITLE
WARNING: Valid values for attribute 'SamAccountName' should end with '$'; the filter clause '(SamAccountName -like  )' may not work as intended.

### ISSUE THREAD

**Issue by Rubeast** [KeysAU/Get-log4j-Windows.ps1#3]
Thx for the script! The Windows-local version works great!
Having a bit trouble to get this one working.

I get following output.
```
PS C:\Windows\system32> C:\support\Get-log4j-Windows.ps1
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
PreReq: Powershell 5.0+. Proceeding..
PreReq: 7-zip tools installed. Proceeding..
PreReq: Credentials Detected. Proceeding..
WARNING: Valid values for attribute 'SamAccountName' should end with '$'; the filter clause '(SamAccountName -like  )' may not work as intended.
Get-ADComputer : The search filter cannot be recognized
At C:\support\Get-log4j-Windows.ps1:88 char:12
+ $Servers = Get-ADComputer -Filter "SamAccountName -like '$($AdCompSea ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADComputer], ADException
    + FullyQualifiedErrorId : ActiveDirectoryServer:8254,Microsoft.ActiveDirectory.Management.Commands.GetADComputer
 
0.) Ping AD servers to make sure online..
Test-Connection : Cannot validate argument on parameter 'ComputerName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\support\Get-log4j-Windows.ps1:120 char:63
+ ...  IF (Test-Connection -BufferSize 32 -Count 1 -ComputerName $_ -Quiet) ...
+                                                                ~~
    + CategoryInfo          : InvalidData: (:) [Test-Connection], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.TestConnectionCommand
 
1.) Complete.
2.) Splitting 0 AD servers into blocks of 1 Servers each..
3.) Complete.
4.) Multi-thread Searching blocks of servers..
5.) Complete.
6.) Building Report Object..
7.) Complete.
8.) --All Complete--
9.) ------------------

```

I changed 
$Domain = (Get-WmiObject Win32_ComputerSystem).Domain 
to
$Domain = (Get-WmiObject Win32_ComputerSystem).mydomain.com

I don't need the multi domain switches. So it's not really clear if I need to change these values.

**Comment by KeysAU** [comment]
You still need the first one, the switch auto detects your domain. So you can copy paste / re use the script in different domains.

The error being generated is that you've not updated the switch correctly. I'll post a screenshot in the morning but that's the issue.

Change this back to 

$Domain = (Get-WmiObject Win32_ComputerSystem).domain and update the 3 lines below to match $Domain

**Comment by KeysAU** [comment]
Just for anyone else getting this error.

The switch part is for people - who have a requirement to run this on multiple domains, and don't want to constantly change the suffix of the reporting, or update the domain information each time. I you only need to run this on a single domain, skip to the end.

What the switch does and how it works:

    $Domain = (Get-WmiObject Win32_ComputerSystem).Domain
Uses the WMI Object to detect your local domain

Depending on what $Domain returns, it sets the following variables - $AdCompSearchPrefix, $DnsDomainSuffix and 
$DnsShortName to whatever you've set them to.

As per the below switch example:

    `switch ($Domain) {    
    "my.fake.domain.com" { 
        $AdCompSearchPrefix = "dev*" #Enter in your AD Computer object prefix eg Dev for DEVAPP001
        $DnsDomainSuffix = ".my.fake.domain.com" # Enter in your Domain names FQDN with a proceeding . 
        $DnsShortName = "FAKE" #Enter in your DNS shorname eg DEV for dev.my.happy.domain.com
    }`

If $Domain = "my.domain.com"
It would not match  "my.fake.domain.com", therefor the 3 variables would be empty, as my.domain.com doesn't have a switch defined above.

If $Domain = "my.fake.domain.com", it would set:

     $AdCompSearchPrefix = "dev*"
     $DnsDomainSuffix = ".my.fake.domain.com"
     $DnsShortName = "FAKE"

==== If you only need to run this on a single domain. ===

Delete the entire switch and just replace it with:

      $AdCompSearchPrefix = "dev*" #Enter in your AD Computer object prefix eg Dev for DEVAPP001
      $DnsDomainSuffix = ".my.fake.domain.com" # Enter in your Domain names FQDN with a proceeding full stop .
      $DnsShortName = "FAKE" #Enter in your DNS shorname eg DEV for dev.my.happy.domain.com

**Comment by Rubeast** [comment]
Thx!
